config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'mains#top'
  resources :mains do
    collection do
      get :top
      get :introduction
    end
  end
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'done'
    end
  end
  resources :articles do
    resources :nices, only: [:create, :destroy]
    member do
      get :map
    end
    collection do
      get :search
    end
  end
  resources :users do
    member do
      get :following
      get :followers
    end
    collection do
      get :sex
      get :age
      get :prefecture
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :move_to_index
  def step1
    @user = User.new
  end

  def step2
    session[:name] = user_params[:name]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:sex] = user_params[:sex]
    session[:age] = user_params[:age]
    session[:prefecture_id] = user_params[:prefecture_id]
    @user = User.new
  end

  def create
    @user = User.new(
      name: session[:name],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      sex: session[:sex],
      age: session[:age],
      prefecture_id: session[:prefecture_id],
    )
    if @user.save
      session[:id] = @user.id
      redirect_to done_signup_index_path
    else
      redirect_to new_user_registration_path
    end

    def done
      @user = User.find(session[:id]) unless user_signed_in?
      sign_in @user
    end
  end

  private

  def move_to_index
    redirect_to root_path if user_signed_in?
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:sex, :age, :prefecture_id)
  end
end

app/views/signup/done.html.haml
.done-data
  = render 'shared/header'

  .done-data__box
    .done-data__box__text
      %p
        登録が完了しました
      %p
        早速記事を投稿してみましょう
    .done-data__box__btn
      = link_to new_article_path, data: {turbolinks: false} do
        %button#articles-index-new-btn
          投稿ページへ

app/views/signup/step1.html.haml
.new-user
  = render "shared/header"
  = form_for @user, url: step2_signup_index_path, method: :get do |f|
    %table.signup-table
      %caption
        ユーザー登録
      %tr
        %th
          お名前
        %td
          = f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "8文字以内" 
      %tr
        %th
          Eメール
        %td
          = f.email_field :email, autocomplete: "email"
      %tr
        %th
          パスワード  
        %td
          = f.password_field :password, autocomplete: "new-password", placeholder: "英数字6文字以上12文字以内"
      %tr
        %th
          パスワードの確認 
        %td
          = f.password_field :password_confirmation, autocomplete: "new-password"
      %tr
        %th
          性別
        %td
          = f.label :sex, :"男性"
          = f.radio_button :sex, :"男性"
          = f.label :sex, :"女性"
          = f.radio_button :sex, :"女性"
          = f.label :sex, :"その他"
          = f.radio_button :sex, :"その他"
      %tr
        %th
          年齢  
        %td
          = f.select :age, options_for_select(User.ages.keys), {}, class: "select-default"
      %tr
        %th
          都道府県
        %td
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, class: "select-default"
    .signup-btns
      = f.button "クリア", type: "reset"
      = f.button "登録する", type: "submit"

app/views/signup/step2.html.haml
.sign-up-step2
  .sign-up-step2__box
    %p.title
      登録情報の確認
    .sign-up-step2__box__sign-up#sign-up-view
      = form_for @user, url: signup_index_path, method: :post do |f|
        .sign-up-step2__box__sign-up__form__name
          .sign-up-step2__box__sign-up__form__name__tag
            ユーザーネーム：
          .sign-up-step2__box__sign-up__form__name__text
            = session[:name]
        .sign-up-step2__box__sign-up__form__email
          .sign-up-step2__box__sign-up__form__email__tag
            メールアドレス：
          .sign-up-step2__box__sign-up__form__email__text
            = session[:email]
        .sign-up-step2__box__sign-up__form__password
          .sign-up-step2__box__sign-up__form__password__tag
            パスワード：
          .sign-up-step2__box__sign-up__form__password__text
            = session[:password]
        .sign-up-step2__box__sign-up__form__sex
          .sign-up-step2__box__sign-up__form__sex__tag
            性別：
          .sign-up-step2__box__sign-up__form__sex__text
            = session[:sex]
        .sign-up-step2__box__sign-up__form__age
          .sign-up-step2__box__sign-up__form__age__tag
            年齢：
          .sign-up-step2__box__sign-up__form__age__text
            = session[:age]
        .sign-up-step2__box__sign-up__form__prefecture
          .sign-up-step2__box__sign-up__form__prefecture__tag
            都道府県：
          .sign-up-step2__box__sign-up__form__prefecture__text
            = Prefecture.find(session[:prefecture_id]).name
        .sign-up-step2__box__sign-up__form__btn#sign-up-btn
          = link_to :back do
            %button#return-btn
              戻る
          = f.button "登録する", type: "submit", id: "sign-up-submit-btn"