config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'mains#top'
  resources :mains do
    collection do
      get :top
      get :introduction
    end
  end
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'done'
    end
  end
  resources :articles do
    resources :nices, only: [:create, :destroy]
    member do
      get :map
    end
    collection do
      get :search
    end
  end
  resources :users do
    member do
      get :following
      get :followers
    end
    collection do
      get :sex
      get :age
      get :prefecture
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  has_many_attached :images
  has_many :nices, dependent: :destroy
  has_many :niced_users, through: :nices, source: :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :map, :search]
  def index
    @articles = Article.all.order("created_at DESC").page(params[:page]).per(8)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.update(image_params)
    @article.save!
    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
    @nice = Nice.new
  end

  def edit
    @article = Article.find(params[:id])
    gon.article = @article
    gon.lat = @article.lat.to_f
    gon.lng = @article.lng.to_f
    img_array = []
    @article.images.each do |image|
      img_array.push(image)
    end
    gon.img_array = img_array
  end

  def update
    @article = Article.find(params[:id])
    if num_params[:num] != nil
      num_params[:num].each do |n|
        n = n.to_i
        @article.images[n].purge
      end
    end
    if image_params[:images] != nil
      @article.update(image_params)
    end
    @article.update(article_params)
    redirect_to article_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy if @article.user_id == current_user.id
    redirect_to articles_path
  end

  def map
    @article = Article.find(params[:id])
    gon.lat = @article.lat.to_f
    gon.lng = @article.lng.to_f
  end

  def search
    if params[:keyword] != ""
      @search_articles = Article.all.where('title LIKE ?', "%#{params[:keyword]}%").order("created_at DESC").limit(8)
    else
      @search_articles = @articles = Article.all.order("created_at DESC").page(request.referer[-1].to_i).per(8)
    end
    respond_to do |format|
      format.json
    end
  end


  private

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end

  def article_params
    params.require(:article).permit(:title, :text, :address, :lat, :lng).merge(user_id: current_user.id)
  end

  def image_params
    params.require(:new_images).permit(images: [])
  end
  
  def num_params
    params.require(:new_images).permit(num: [])
  end
end

app/views/articles/edit.html.haml
.new-article
  = render 'shared/header'

  = form_with model: @article, local: true, id: "form_with_edit" do |f|
    .new-article__box
      .new-article__box__left
        %p.new-article__box__left__header
          登録したい地点をクリックするか検索をして
          %span
            ピン
          をつけよう。
        %p.new-article__box__left__text
          住所や駅名、目印などで検索できます。
        #map-search
          %input{type: "text", value: "",placeholder: "例)東京駅", id: "search",autofocus: "ture"}
          %button{type: "button", value: "検索", id: "map_button"}
            .icon-search
        #map
        .new-article__box__left__bottom#article-map-bottom
          %p.new-article__box__left__bottom__text
            地図上をクリックするとピンを指定できます。
        = f.text_field :lat, id: "lat", value: "", type: "hidden"
        = f.text_field :lng, id: "lng", value: "", type: "hidden"
        = f.text_field :address, id: "address", value: "", type: "hidden"
        %script{src: "https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=" + Rails.application.credentials.dig(:google, :google_api_key).to_s + "&callback=editMap", async: "", defer: "defer"} }

      .new-article__box__modal#article-map-modal
        .new-article__box__modal__inner#modal-gray
        .new-article__box__modal__right
          .new-article__box__modal__right__form
            %p.new-article__box__modal__right__form__header
              新規投稿
            .new-article__box__modal__right__form__title
              =f.label :title, "タイトル"
              %span.require
                必須
              =f.text_field :title, placeholder: '記事のタイトルを入力してください', class: 'form-default', maxlength: "30"
            .new-article__box__modal__right__form__image
              =f.label :images, id: "article-images" do
                .icon-new-images
                  クリックすると画像が選べます(1〜3枚まで)
                  %span.require
                    必須
              =f.file_field :images, multiple: true, class: 'file_image', accept: "image/jpeg, image/png"
            %p#image-preview
              ※画像を添付した場合プレビューが表示されます
            .new-article__box__modal__right__form__preview#preview_box
              %ul#preview_list
                - i = 0
                - @article.images[0..2].each do |image|
                  %li.upload-article{id: i}
                    - i += 1
                    %figure.upload-article-figure
                      = image_tag(image)
                    .upload-article-btn
                      %a.upload-article-delete="削除"
            .new-article__box__modal__right__form__text
              =f.label :text, "テキスト"
              %span.require
                必須
              =f.text_area :text, placeholder: '記事の内容を入力してください', rows: "4"
            .new-article__box__modal__right__form__submit
              =f.submit '投稿する', id: "article-submit"

app/views/articles/index.html.haml
.articles-index
  = render 'shared/header'

  .articles-index__box
    - if @articles.present?
      .articles-index__box__show
        .articles-index__box__show__title
          .articles-index__box__show__title__list
            %p#articles-index-title
              記事一覧
            .articles-index__box__show__title__list__search
              %input#articles-input-search
              .search-btn
                .icon-search#articles-index-search
          %span
      .articles-index__box__main
        - @articles.each do |article|
          .articles-index__box__main__container
            .articles-index__box__main__container__list#article-index-list
              = link_to article_path(article.id), data: {turbolinks: false} do
                .articles-index__box__main__container__list__image#index-list-image
                  = image_tag(article.images[0])
                .articles-index__box__main__container__list__inset-border
                .articles-index__box__main__container__list__date
                  .icon-calender
                  .articles-index__box__main__container__list__date__text
                    = article.created_at.strftime("%Y/%m/%d(%a)")
                .articles-index__box__main__container__list__nice
                  .icon-heart
                  .articles-index__box__main__container__list__nice__count
                    = article.nices.count
                .articles-index__box__main__container__list__title
                  = article.title.truncate(18, ommision: "...")
                %span.articles-index__box__main__container__list__line
                .articles-index__box__main__container__list__user-name
                  = article.user.name
                .articles-index__box__main__container__list__text
                  = article.text.truncate(34, ommision: "...")
                .articles-index__box__main__container__list__wrap#mouse-offset
      .articles-index__box__paginate
        =paginate(@articles)
    - else
      .articles-index__box__no-show
        .articles-index__box__no-show__view
          .articles-index__box__no-show__view__text
            %p
              記事が投稿されていません
            %p
              気軽に投稿してみましょう
          - if user_signed_in?
            .articles-index__box__no-show__view__btn
              = link_to new_article_path, data: {turbolinks: false} do
                %button#articles-index-new-btn
                  投稿ページへ
          - else
            .articles-index__box__no-show__view__btn
              = link_to step1_signup_index_path, data: {turbolinks: false} do
                %button#articles-index-signup-btn
                  ユーザー登録
              = link_to new_user_session_path, data: {turbolinks: false} do
                %button#articles-index-log-in-btn
                  ログイン

app/views/articles/map.html.haml
#article-map

%script{src: "https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=" + Rails.application.credentials.dig(:google, :google_api_key).to_s + "&callback=articleMap", async: "", defer: "defer"} }

app/views/articles/new.html.haml
.new-article
  = render 'shared/header'

  = form_with model: @article, local: true, id: "form_with" do |f|
    .new-article__box
      .new-article__box__left
        %p.new-article__box__left__header
          登録したい地点をクリックするか検索をして
          %span
            ピン
          をつけよう。
        %p.new-article__box__left__text
          住所や駅名、目印などで検索できます。
        #map-search
          %input{type: "text", value: "",placeholder: "例)東京駅", id: "search",autofocus: "ture"}
          %button{type: "button", value: "検索", id: "map_button"}
            .icon-map-search
        #map
        .new-article__box__left__bottom#article-map-bottom
          %p.new-article__box__left__bottom__text
            地図上をクリックするとピンを指定できます。
        = f.text_field :lat, id: "lat", value: "", type: "hidden"
        = f.text_field :lng, id: "lng", value: "", type: "hidden"
        = f.text_field :address, id: "address", value: "", type: "hidden"
        %script{src: "https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=" + Rails.application.credentials.dig(:google, :google_api_key).to_s + "&callback=initMap", async: "", defer: "defer"} }

      .new-article__box__modal#article-map-modal
        .new-article__box__modal__inner#modal-gray
        .new-article__box__modal__right
          .new-article__box__modal__right__form
            %p.new-article__box__modal__right__form__header
              新規投稿
            .new-article__box__modal__right__form__title
              =f.label :title, "タイトル"
              %span.require
                必須
              =f.text_field :title, placeholder: '記事のタイトルを入力してください', class: 'form-default', maxlength: "30"
            .new-article__box__modal__right__form__image
              =f.label :images, id: "article-images" do
                .icon-new-images
                .new-article__box__modal__right__form__image__text
                  %p
                    クリックすると画像が選べます(1〜3枚まで)
                  %span.require
                    必須
              =f.file_field :images, multiple: true, class: 'file_image', accept: "image/jpeg, image/png"
            %p#image-preview
              ※画像を添付した場合プレビューが表示されます
            .new-article__box__modal__right__form__preview#preview_box
              %ul#preview_list
            .new-article__box__modal__right__form__text
              =f.label :text, "テキスト"
              %span.require
                必須
              =f.text_area :text, placeholder: '記事の内容を入力してください', rows: "4"
            .new-article__box__modal__right__form__submit
              =f.submit '投稿する', id: "article-submit"

app/views/articles/show.html.haml
.article-show
  = render 'shared/header'

  .article-show__box
    .article-show__box__top
      .article-show__box__top__left
        .article-show__box__top__left__lists
          .article-show__box__top__left__lists__title
            = @article.title
          .article-show__box__top__left__lists__user
            .article-show__box__top__left__lists__user__name
              %p
                ユーザー名
              = link_to user_path(@article.user.id), data: {turbolinks: false} do
                = @article.user.name
            .article-show__box__top__left__lists__user__sex
              %p
                性別
              = link_to sex_users_path(sex: @article.user.sex), data: {turbolinks: false} do
                = @article.user.sex
            .article-show__box__top__left__lists__user__age
              %p
                年齢
              = link_to age_users_path(age: @article.user.age), data: {turbolinks: false} do
                = @article.user.age
            .article-show__box__top__left__lists__user__prefecture
              %p
                都道府県
              = link_to prefecture_users_path(prefecture: @article.user.prefecture_id), data: {turbolinks: false} do
                = @article.user.prefecture.name
          .article-show__box__top__left__lists__address
            %p
              住所
            = @article.address
          .article-show__box__top__left__lists__map
            .article-show__box__top__left__lists__map__text
              場所の詳細はボタンをクリック
            .article-show__box__top__left__lists__map__btn
              = link_to map_article_path(@article), data: {turbolinks: false} do
                %button#article-show-map
                  地図を表示
          .article-show__box__top__left__lists__nice
            .article-show__box__top__left__lists__nice__btn
              - if user_signed_in? && @article.user_id != current_user.id
                - if current_user.already_niced?(@article)
                  = button_to article_nice_path(@article), method: 'delete' do
                    .icon-article-show-niced
                    %p
                      取消
                - else
                  = button_to article_nices_path(@article) do
                    .icon-article-show-nice
                    %p
                      いいね
              - elsif user_signed_in? && @article.user_id == current_user.id
                %ul
                  %li
                    = link_to edit_article_path(@article.id), id: "article-edit", data: {turbolinks: false} do
                      .icon-article-edit
                      %p
                        編集
                  %li
                    = link_to article_path, id: "article-delete", method: "delete" do
                      .icon-article-delete
                      %p
                        削除
      .article-show__box__top__right
        .article-show__box__top__right__image
          %ul.article-show__box__top__right__image__view#slide-lists
            - @article.images.each do |image|
              %li.article-show__box__top__right__image__view__list#slide-list
                = image_tag(image)
            %ul.article-show__box__top__right__image__view__btn#image-btn-list
              - if @article.images.count != 0 && @article.images.count != 1
                - @article.images.each_with_index do |image, index|
                  .article-show__box__top__right__image__view__btn__list#image-btn
                    - if index == 0
                      = image_tag(image, text: "#{index + 1}", class: "target")
                    - else
                      = image_tag(image, text: "#{index + 1}")
          - if @article.images.count != 0 && @article.images.count != 1
            .article-show__box__top__right__image__prev#prev-btn
              .article-show__box__top__right__image__prev__arrow
              .icon-left-arrow
            .article-show__box__top__right__image__next#next-btn
              .article-show__box__top__right__image__next__arrow
              .icon-right-arrow
    .article-show__box__bottom
      .article-show__box__bottom__text
        = simple_format(@article.text)
    