config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'mains#top'
  resources :mains do
    collection do
      get :top
      get :introduction
    end
  end
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'done'
    end
  end
  resources :articles do
    resources :nices, only: [:create, :destroy]
    member do
      get :map
    end
    collection do
      get :search
    end
  end
  resources :users do
    member do
      get :following
      get :followers
    end
    collection do
      get :sex
      get :age
      get :prefecture
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :nices, dependent: :destroy
  has_many :niced_articles, through: :nices, source: :article
  def already_niced?(article)
    self.nices.exists?(article_id: article.id)
  end
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: { maximum: 8 }
  validates :password, presence: true, length: { maximum: 12 }
  validates :profile, length: { maximum: 100 }
  
    # ユーザーをフォローする
    def follow(other_user)
      active_relationships.create(followed_id: other_user.id)
    end
   
    # ユーザーをアンフォローする
    def unfollow(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
    end
   
    # 現在のユーザーがフォローしていたらtrueを返す
    def following?(other_user)
      following.include?(other_user)
    end

  enum age: {
    "---": nil,
    "〜１０代": 0,
    "２０代": 1,
    "３０代": 2,
    "４０代": 3,
    "５０代": 4,
    "６０代〜": 5
  }, _prefix: true
    
  enum sex: {
    "---": nil,
    "男性": 0,
    "女性": 1,
    "その他": 2
  }, _prefix: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
    @articles_count = @user.articles
    @articles = @user.articles.order("created_at DESC").page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.update(image_params) if @user.id == current_user.id
    redirect_to user_path(@user.id)
  end

  def destroy
    sign_out @user
    session[:root] = "on"
    redirect_to root_path
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def sex
    @users = User.where(sex: params[:sex]).page(params[:page]).per(6)
    @users.each do |user|
      @user = user.sex
    end
  end
  
  def age
    @users = User.where(age: params[:age]).page(params[:page]).per(6)
    @users.each do |user|
      @user = user.age
    end
  end

  def prefecture
    @users = User.where(prefecture_id: params[:prefecture]).page(params[:page]).per(6)
    @users.each do |user|
      @user = user.prefecture.name
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :sex, :age, :prefecture_id, :profile)
  end

  def image_params
    params.require(:user).permit(:image)
  end

end

app/views/users/age.html.haml
.user-index
  = render 'shared/header'

  .user-index__box
    .user-index__box__title
      %p.user-index__box__title__text
        = "#{@user} のユーザー一覧"
    %ul.user-index__box__users#users-list
      -@users.each do |user|
        %li.user-index__box__users__list
          = link_to user_path(user.id), class: "user-index__box__users__list__main", data: {turbolinks: false} do
            .user-index__box__users__list__image
              - if user.image.attached?
                = image_tag(user.image, class: "user-image")
              - else
                = image_tag("user_no-image.png", class: "user-image")
            .user-index__box__users__list__name
              = user.name
          .user-index__box__users__list__sub
            = link_to sex_users_path(sex: user.sex), class: "user-index__box__users__list__sub__sex", data: {turbolinks: false} do
              .user-index__box__users__list__sub__sex__text
                = user.sex
            = link_to age_users_path(age: user.age), class: "user-index__box__users__list__sub__age", data: {turbolinks: false} do
              .user-index__box__users__list__sub__age__text
                = user.age
            = link_to prefecture_users_path(prefecture: user.prefecture_id), class: "user-index__box__users__list__sub__prefecture", data: {turbolinks: false} do
              .user-index__box__users__list__sub__prefecture__text
                = user.prefecture.name
    .user-index__box__paginate
      = paginate(@users)

app/views/users/edit.html.haml
.user-edit
  = render 'shared/header'
  = image_tag('top-bg.jpg', class: "user-edit-image")
  .user-edit__box
    = form_with model: @user, local: true, class: "user-edit__box__form" do |f|
      .user-edit__box__form__table
        .user-edit__box__form__table__title
          ユーザー情報の編集
        .user-edit__box__form__table__name
          .user-edit__box__form__table__name__header
            お名前
          .user-edit__box__form__table__name__input
            = f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "8文字以内"
        .user-edit__box__form__table__image
          .user-edit__box__form__table__image__header
            画像
          .user-edit__box__form__table__image__input
            =f.label :image, id: "user-image" do
              .icon-new-images
                クリックすると画像が選べ、選び直すと切り替わります
            =f.file_field :image, class: 'file_image', accept: "image/jpeg, image/png"
        .user-edit__box__form__table__preview
          .user-edit__box__form__table__preview__header
            プレビュー
          .user-edit__box__form__table__preview__input#preview_box
            #preview_list
        .user-edit__box__form__table__sex
          .user-edit__box__form__table__sex__header
            性別
          .user-edit__box__form__table__sex__input
            = f.label :sex, :"男性"
            = f.radio_button :sex, :"男性"
            = f.label :sex, :"女性"
            = f.radio_button :sex, :"女性"
            = f.label :sex, :"その他"
            = f.radio_button :sex, :"その他"
        .user-edit__box__form__table__list
          .user-edit__box__form__table__list__age
            .user-edit__box__form__table__list__age__header
              年齢
            .user-edit__box__form__table__list__age__input
              = f.select :age, options_for_select(User.ages.keys), {}, class: "select-default"
          .user-edit__box__form__table__list__prefecture
            .user-edit__box__form__table__list__prefecture__header
              都道府県
            .user-edit__box__form__table__list__prefecture__input
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name, class: "select-default"
        .user-edit__box__form__table__profile
          .user-edit__box__form__table__profile__header
            自己紹介
          .user-edit__box__form__table__profile__input
            = f.text_area :profile, placeholder: "自己紹介文 最大100文字"
        .user-edit__box__form__table__submit
          = f.button "クリア", type: "reset", class: "user-edit-reset-btn"
          = f.button "登録する", type: "submit", class: "user-edit-submit-btn"

app/views/users/index.html.haml
.user-index
  = render 'shared/header'

  .user-index__box
    .user-index__box__title
      %p.user-index__box__title__text
        ユーザー一覧
    %ul.user-index__box__users#users-list
      -@users.each do |user|
        %li.user-index__box__users__list#user-list
          = link_to user_path(user.id), class: "user-index__box__users__list__main", data: {turbolinks: false} do
            .user-index__box__users__list__image#user-image
              - if user.image.attached?
                = image_tag(user.image, class: "user-image")
              - else
                = image_tag("user_no-image.png", class: "user-image")
            .user-index__box__users__list__name
              = user.name
          .user-index__box__users__list__sub
            = link_to sex_users_path(sex: user.sex), class: "user-index__box__users__list__sub__sex", data: {turbolinks: false} do
              .user-index__box__users__list__sub__sex__text
                = user.sex
            = link_to age_users_path(age: user.age), class: "user-index__box__users__list__sub__age", data: {turbolinks: false} do
              .user-index__box__users__list__sub__age__text
                = user.age
            = link_to prefecture_users_path(prefecture: user.prefecture_id), class: "user-index__box__users__list__sub__prefecture", data: {turbolinks: false} do
              .user-index__box__users__list__sub__prefecture__text
                = user.prefecture.name
    .user-index__box__paginate
      = paginate(@users)

app/views/users/prefecture.html.haml
.user-index
  = render 'shared/header'

  .user-index__box
    .user-index__box__title
      %p.user-index__box__title__text
        = "#{@user} のユーザー一覧"
    %ul.user-index__box__users#users-list
      -@users.each do |user|
        %li.user-index__box__users__list
          = link_to user_path(user.id), class: "user-index__box__users__list__main", data: {turbolinks: false} do
            .user-index__box__users__list__image
              - if user.image.attached?
                = image_tag(user.image, class: "user-image")
              - else
                = image_tag("user_no-image.png", class: "user-image")
            .user-index__box__users__list__name
              = user.name
          .user-index__box__users__list__sub
            = link_to sex_users_path(sex: user.sex), class: "user-index__box__users__list__sub__sex", data: {turbolinks: false} do
              .user-index__box__users__list__sub__sex__text
                = user.sex
            = link_to age_users_path(age: user.age), class: "user-index__box__users__list__sub__age", data: {turbolinks: false} do
              .user-index__box__users__list__sub__age__text
                = user.age
            = link_to prefecture_users_path(prefecture: user.prefecture_id), class: "user-index__box__users__list__sub__prefecture", data: {turbolinks: false} do
              .user-index__box__users__list__sub__prefecture__text
                = user.prefecture.name
    .user-index__box__paginate
      = paginate(@users)

app/views/users/sex.html.haml
.user-index
  = render 'shared/header'

  .user-index__box
    .user-index__box__title
      %p.user-index__box__title__text
        = "#{@user} のユーザー一覧"
    %ul.user-index__box__users#users-list
      -@users.each do |user|
        %li.user-index__box__users__list
          = link_to user_path(user.id), class: "user-index__box__users__list__main", data: {turbolinks: false} do
            .user-index__box__users__list__image
              - if user.image.attached?
                = image_tag(user.image, class: "user-image")
              - else
                = image_tag("user_no-image.png", class: "user-image")
            .user-index__box__users__list__name
              = user.name
          .user-index__box__users__list__sub
            = link_to sex_users_path(sex: user.sex), class: "user-index__box__users__list__sub__sex", data: {turbolinks: false} do
              .user-index__box__users__list__sub__sex__text
                = user.sex
            = link_to age_users_path(age: user.age), class: "user-index__box__users__list__sub__age", data: {turbolinks: false} do
              .user-index__box__users__list__sub__age__text
                = user.age
            = link_to prefecture_users_path(prefecture: user.prefecture_id), class: "user-index__box__users__list__sub__prefecture", data: {turbolinks: false} do
              .user-index__box__users__list__sub__prefecture__text
                = user.prefecture.name
    .user-index__box__paginate
      = paginate(@users)

app/views/users/show.html.haml
.user-show
  = render 'shared/header'

  .user-show__box
    .user-show__box__left
      .user-show__box__left__user
        .user-show__box__left__user__image
          -if @user.image.attached?
            = image_tag(@user.image)
          -else
            = image_tag("user_no-image.png")
        .user-show__box__left__user__name
          = @user.name
        .user-show__box__left__user__sex
          %p
            性別：
          .user-show__box__left__user__sex__text
            = @user.sex
        .user-show__box__left__user__age
          %p
            年齢：
          .user-show__box__left__user__age__text
            = @user.age
        .user-show__box__left__user__prefecture
          %p
            都道府県：
          .user-show__box__left__user__prefecture__text
            = @user.prefecture.name
        .user-show__box__left__user__profile
          %p
            自己紹介
          .user-show__box__left__user__profile__text
            = @user.profile
        .user-show__box__left__user__menu
          -if user_signed_in? && @user.id == current_user.id
            %ul
              %li
                = link_to edit_user_path(@user.id), id: "user-edit" do
                  .icon-user-edit
                  %p
                    編集
        .user-show__box__left__user__articles
          = link_to root_path, class: "user-box__follow__articles-link" do
            .icon-user-article
            %p
              = "articles: #{@user.articles.count}"
          = link_to root_path, class: "user-box__follow__nices-link" do
            .icon-nice-users
            %p
              = "nices: #{@user.niced_articles.count}"
        .user-show__box__left__user__follow
          = link_to following_user_path(@user), class: "user-box__follow__following-link" do
            .icon-following-users
            %p
              = "following: #{@user.following.count}"
          = link_to followers_user_path(@user), class: "user-box__follow__followers-link" do
            .icon-followers-users
            %p
              = "followers: #{@user.followers.count}"
        - if user_signed_in? && current_user != @user
          - if current_user.following?(@user)
            = form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: {method: :delete}) do |f|
              = f.submit 'フォロー取消', class: "btn unfollow"
          - else
            = form_for(current_user.active_relationships.build) do |f|
              %div= hidden_field_tag :followed_id, @user.id
              = f.submit "フォローする", class: "btn btn-primary"
    .user-show__box__right
      .user-show__box__right__info
        .user-show__box__right__info__tab-top
          .user-show__box__right__info__tab-top__wave#tab-top
            = image_tag("tab-top.svg")
        %ul.user-show__box__right__info__tab#tab-list
          %li.user-show__box__right__info__tab__menu.active#user-articles
            .user-show__box__right__info__tab__menu__circle
            .icon-user-article#tab-icon
            .user-show__box__right__info__tab__menu__articles#tab-articles-count
              = @user.articles.count
          %li.user-show__box__right__info__tab__menu#nice-users
            .user-show__box__right__info__tab__menu__circle
            .icon-nice-users#tab-icon
            .user-show__box__right__info__tab__menu__nices#tab-nices-count
              = @user.niced_articles.count
          %li.user-show__box__right__info__tab__menu#following-users
            .user-show__box__right__info__tab__menu__circle
            .icon-following-users#tab-icon
            .user-show__box__right__info__tab__menu__following#tab-following-count
              = @user.following.count
          %li.user-show__box__right__info__tab__menu#followers-users
            .user-show__box__right__info__tab__menu__circle
            .icon-followers-users#tab-icon
            .user-show__box__right__info__tab__menu__followers#tab-followers-count
              = @user.followers.count
      .user-show__box__right__view
        .user-show__box__right__view__list#tab-views
          %ul.user-show__box__right__view__list__articles#slide-lists
            - if @articles.present?
              - @articles.each do |article|
                %li.user-show__box__right__view__list__articles__show#slide-list
                  = link_to article_path(article.id) do
                    = image_tag(article.images[0])
                    .user-show__box__right__view__list__articles__show__created-at
                      .icon-calender
                      .user-show__box__right__view__list__articles__show__created-at__text
                        = article.created_at.strftime("%Y/%m/%d(%a)")
                    .user-show__box__right__view__list__articles__show__title
                      = article.title.truncate(15, ommision: "...")
                    %span.user-show__box__right__view__list__articles__show__line
                    .user-show__box__right__view__list__articles__show__user-name
                      = article.user.name
                    .user-show__box__right__view__list__articles__show__text
                      = article.text.truncate(75, ommision: "...")
                  .user-show__box__right__view__list__articles__show__nice#article-nice-box
                    - if user_signed_in? && article.user_id != current_user.id
                      - if current_user.already_niced?(article)
                        = button_to article_nice_path(article), method: 'delete', class: "nice-btn active" do
                          .icon-nice-btn
                      -else
                        = button_to article_nices_path(article), class: "nice-btn" do
                          .icon-nice-btn
                    -else
                      .icon-heart
                    .user-show__box__right__view__list__articles__show__nice__count
                      = article.nices.count
            - else
              .user-show__box__right__view__list__articles__no-show
                .user-show__box__right__view__list__articles__no-show__text
                  投稿した記事がありません
            - if @articles_count.count > 5
              .user-show__box__right__view__list__articles__paginate
                =paginate(@articles)
            .user-show__box__right__view__list__articles__btn
              .user-show__box__right__view__list__articles__btn__list#article-slide-btn-list
                - @articles.each_with_index do |article, index|
                  - if index < 5
                    .user-show__box__right__view__list__articles__btn__list__dot#user-article-slide-btn
                      - if index == 0
                        = link_to "#{index + 1}", "/" ,class:"target"
                      - else
                        = link_to "#{index + 1}", "/"
            - if @articles_count.count != 0 && @articles_count.count != 1
              .user-show__box__right__view__list__articles__prev#prev-btn
                .user-show__box__right__view__list__articles__prev__arrow
                .icon-left-arrow
              .user-show__box__right__view__list__articles__next#next-btn
                .user-show__box__right__view__list__articles__next__arrow
                .icon-right-arrow
          .user-show__box__right__view__list__nices#nices-box
            - if @user.niced_articles.present?
              .user-show__box__right__view__list__nices__exist
                - @user.niced_articles.each do |niced_article|
                  = link_to article_path(niced_article.id), data: {turbolinks: false} do
                    %li.user-show__box__right__view__list__nices__exist__list
                      .user-show__box__right__view__list__nices__exist__list__left
                        .user-show__box__right__view__list__nices__exist__list__left__image
                          = image_tag(niced_article.images[0])
                      .user-show__box__right__view__list__nices__exist__list__right
                        %ul.user-show__box__right__view__list__nices__exist__list__right__top
                          %li.user-show__box__right__view__list__nices__exist__list__right__top__title
                            %p
                              タイトル：
                            = niced_article.title.truncate(20, ommision: "...")
                        .user-show__box__right__view__list__nices__exist__list__right__bottom
                          .user-show__box__right__view__list__nices__exist__list__right__bottom__text
                            = niced_article.text.truncate(100, ommision: "...")
            - else
              .user-show__box__right__view__list__nices__not-exist
                .user-show__box__right__view__list__nices__not-exist__text
                  いいね！した記事はありません
          .user-show__box__right__view__list__following#following-box
            - if @user.following.present?
              %ul.user-show__box__right__view__list__following__exist
                - @user.following.each do |following|
                  = link_to user_path(following.id), data: {turbolinks: false} do
                    %li.user-show__box__right__view__list__following__exist__list
                      .user-show__box__right__view__list__following__exist__list__left
                        .user-show__box__right__view__list__following__exist__list__left__image
                          -if following.image.attached?
                            = image_tag(following.image)
                          -else
                            = image_tag("user_no-image.png")
                      .user-show__box__right__view__list__following__exist__list__right
                        %ul.user-show__box__right__view__list__following__exist__list__right__top
                          %li.user-show__box__right__view__list__following__exist__list__right__top__name
                            = following.name
                          %li.user-show__box__right__view__list__following__exist__list__right__top__sex
                            = following.sex
                          %li.user-show__box__right__view__list__following__exist__list__right__top__age
                            = following.age
                          %li.user-show__box__right__view__list__following__exist__list__right__top__prefecture
                            = following.prefecture.name
                        .user-show__box__right__view__list__following__exist__list__right__bottom
                          .user-show__box__right__view__list__following__exist__list__right__bottom__profile
                            - if following.profile.present?
                              = following.profile.truncate(100, ommision: "...")
            - else
              .user-show__box__right__view__list__following__not-exist
                .user-show__box__right__view__list__following__not-exist__text
                  フォローしたユーザーはいません
          .user-show__box__right__view__list__followers#followers-box
            - if @user.followers.present?
              %ul.user-show__box__right__view__list__followers__exist
                - @user.followers.each do |follower|
                  = link_to user_path(follower.id), data: {turbolinks: false} do
                    %li.user-show__box__right__view__list__followers__exist__list
                      .user-show__box__right__view__list__followers__exist__list__left
                        .user-show__box__right__view__list__followers__exist__list__left__image
                          -if follower.image.attached?
                            = image_tag(follower.image)
                          -else
                            = image_tag("user_no-image.png")
                      .user-show__box__right__view__list__followers__exist__list__right
                        %ul.user-show__box__right__view__list__followers__exist__list__right__top
                          %li.user-show__box__right__view__list__followers__exist__list__right__top__name
                            = follower.name
                          %li.user-show__box__right__view__list__followers__exist__list__right__top__sex
                            = follower.sex
                          %li.user-show__box__right__view__list__followers__exist__list__right__top__age
                            = follower.age
                          %li.user-show__box__right__view__list__followers__exist__list__right__top__prefecture
                            = follower.prefecture.name
                        .user-show__box__right__view__list__followers__exist__list__right__bottom
                          .user-show__box__right__view__list__followers__exist__list__right__bottom__profile
                            - if follower.profile.present?
                              = follower.profile.truncate(100, ommision: "...")
            - else
              .user-show__box__right__view__list__followers__not-exist
                .user-show__box__right__view__list__followers__not-exist__text
                  フォロワーはいません

app/views/users/show_follow.html.haml
.user-show-follow
  = render 'shared/header'

  .user-show-follow__box
    .user-show-follow__box__title
      = "#{@user.name} さんのフォロー"
    - @user.following.each do |user|
      .user-show-follow__box__list
        %ul
          %li
            = link_to "#{user.name}", user_path(user), data: {turbolinks: false}

app/views/users/show_follower.html.haml
.user-show-follower
  = render 'shared/header'

  .user-show-follower__box
    .user-show-follower__box__title
      = "#{@user.name} さんのフォロワー"
    - @user.followers.each do |user|
      .user-show-follower__box__list
        %ul
          %li
            = link_to "#{user.name}", user_path(user), data: {turbolinks: false}