config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'mains#top'
  resources :mains do
    collection do
      get :top
      get :introduction
    end
  end
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'done'
    end
  end
  resources :articles do
    resources :nices, only: [:create, :destroy]
    member do
      get :map
    end
    collection do
      get :search
    end
  end
  resources :users do
    member do
      get :following
      get :followers
    end
    collection do
      get :sex
      get :age
      get :prefecture
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_header.html.haml
.main-header
  .header
    .header__icon
      .header__icon__box
        %ul.header__icon__box__lists#menu-lists
          %li.header__icon__box__lists__title#header-title
            = link_to root_path, class: "header-menu-icon", data: {turbolinks: false} do
              .header-menu-icon-top
                %p
                  GPS-Tweet
              %span.menu-under-bar
          %li.header__icon__box__lists__articles#header-articles
            = link_to articles_path, class: "header-menu-icon", data: {turbolinks: false} do
              .header-menu-icon-top
                %p
                  Articles
              %span.menu-under-bar
          %li.header__icon__box__lists__users#header-users
            = link_to users_path, class: "header-menu-icon", data: {turbolinks: false} do
              .header-menu-icon-top
                %p
                  Users
                  %span.menu-under-bar
          - if user_signed_in?
            %li.header__icon__box__lists__post#header-post
              = link_to new_article_path, class: "header-menu-icon", data: {turbolinks: false} do
                .header-menu-icon-top
                  %p
                    Post
                %span.menu-under-bar
            %li.header__icon__box__lists__logout#header-logout{data:"user"}
              = link_to user_path(current_user.id), method: "delete", class: "header-menu-icon", data: {turbolinks: false} do
                .header-menu-icon-top
                  %p
                    Log out
                %span.menu-under-bar
          - else
            %li.header__icon__box__lists__login#header-login{data:"user"}
              = link_to new_user_session_path, class: "header-menu-icon", data: {turbolinks: false} do
                .header-menu-icon-top
                  %p
                    Log in
                %span.menu-under-bar
            %li.header__icon__box__lists__signup#header-signup{data:"user"}
              = link_to step1_signup_index_path, class: "header-menu-icon", data: {turbolinks: false} do
                .header-menu-icon-top
                  %p
                    Sign up
                %span.menu-under-bar
      %ul.header__icon__explain
      %button.header__icon__first#menu-first
        %span.three-first-bar
      %button.header__icon__open#menu-icon
        %span.three-open-bar
      %ul.header__icon__top__lists
        - if user_signed_in?
          %li.header__icon__top__lists__current
            = link_to user_path(current_user.id) , method: "get", class: "header-menu-icon", data: {turbolinks: false} do
              %p
                = "ようこそ #{current_user.name} さん"
        -else
          %li.header__icon__top__lists__how
            = link_to introduction_mains_path, class: "header-menu-icon", data: {turbolinks: false} do
              %p
                はじめに
        %li.header__first__lists__top
          = link_to root_path, class: "header-menu-icon", data: {turbolinks: false} do
            %p
              GPS-Tweet
    .header__explain#header-explain
      %P#header-title-explain
        "トップページへ戻ります"
      %p#header-articles-explain
        "投稿記事の一覧を表示します"
      %p#header-users-explain
        "ユーザーの一覧を表示します"
      %p#header-post-explain
        "記事投稿ページを表示します"
      %p#header-logout-explain
        "ログアウトします"
      %p#header-login-explain
        "ログイン画面を表示します"
      %p#header-signup-explain
        "ユーザー登録画面を表示します"